### ISSUE TITLE
README Tweaks

### ISSUE THREAD

**Issue by gagbo** [autometrics-dev/autometrics-rs#142]
The "For projects already using custom Prometheus metrics" section could use a few tweaks, noting them here not to forget.

- The toml snippet to add autometrics doesn't work. "Inline tables" need to be on a single line, not multiple ones, at least my version of Cargo didn't want to accept the current form as is. we should rather have a single line version
```toml
[dependencies]
autometrics = { version = "*", features = ["prometheus-0_13"], default-features = false }
```
- The "Configure autometrics" link goes to https://docs.rs/autometrics/latest/autometrics/#metrics-libraries and as of today the anchor does not exist on the docs.rs page so it only jumps to the top of the documentation which makes the link less helpful.
