### ISSUE TITLE
Autometrics `prometheus-exporter` is not compatible with `axum` 0.7

### ISSUE THREAD

**Issue by ferrohd** [autometrics-dev/autometrics-rs#166]
The repro below is a simplified version of the [example](https://github.com/autometrics-dev/autometrics-rs/tree/1c6ae63ff061d0df17654d7f429df99474fcdfe4/examples/axum) found in the repo

`Cargo.toml`

```toml
[package]
name = "axum-repro"
version = "0.1.0"
edition = "2021"

[dependencies]
autometrics = {version = "1.0.0", features = ["prometheus-exporter"]}
axum = "0.7.1"
tokio = {version="1.34.0", features = ["full"]}
``` 

`main.rs`

```rust
use std::net::SocketAddr;

use axum::{routing::get, Router};
use autometrics::prometheus_exporter;

#[tokio::main]
pub async fn main() {
    prometheus_exporter::init();
    let app = Router::new()
        .route(
            "/metrics",
            get(|| async { prometheus_exporter::encode_http_response() }),
        );

    let addr = SocketAddr::from(([127, 0, 0, 1], 3000));
    let tcp_listen = tokio::net::TcpListener::bind(&addr).await.unwrap();
    axum::serve(tcp_listen, app.into_make_service()).await.unwrap();
}

```
